services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    privileged: true
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local
